version: "2"
linters:
  enable:
    - dupl
    - gosec
    - nakedret
    - whitespace
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet
  settings:
    dupl:
      threshold: 250
  exclusions:
    generated: lax
    rules:
      - text: 'ST1003:'
        linters:
          - staticcheck
      - text: 'G101:'
        linters:
          - gosec
        path: '_test\.go$'
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
