# Regenerates JSON schema whenever a PR is merged to main
name: Generate JSON

on: pull_request

# Needs write permissions to write the schema to the repo
permissions:
  contents: write

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make generate-json
      - run: |
          if [[ `git status --porcelain` ]]; then
            echo "[bot] Schema changes detected, committing."
            # git sha != sha1: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects
            sha=$(gh api -X GET repos/{owner}/{repo}/contents/$SCHEMA_FILE -F ref="${HEAD_REF}"" --jq '.sha')
            b64=$(cat $SCHEMA_FILE | base64)
            gh api -X PUT repos/{owner}/{repo}/contents/$SCHEMA_FILE -F branch="${HEAD_REF}" \
            -F content="$b64" -F sha="$sha" -F message='docs: update json schema file'
          else
            echo "[bot] No schema changes detected, nothing to commit."
          fi
        env:
          SCHEMA_FILE: docs/schema.json
          GH_TOKEN: ${{ github.token }}
          HEAD_REF: ${{ github.head_ref }}
